name: CI 

on:
  workflow_dispatch:

jobs:
  pack:
    uses: ./.github/workflows/pack.yml
    secrets:
      GH_ACTIONS_AWS_ACCESS_KEY_ID: ${{ secrets.GH_ACTIONS_AWS_ACCESS_KEY_ID }}
      GH_ACTIONS_AWS_SECRET_ACCESS_KEY: ${{ secrets.GH_ACTIONS_AWS_SECRET_ACCESS_KEY }}
    if: ${{ github.event_name == 'workflow_dispatch' }}
    with:
      node_version: "22"
      semantic_version: "23.0.7"
      image_name_ecr_login: ${{ github.event.repository.name }}-login

